# Generated by Django 5.2 on 2025-05-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_plub',
            new_name='data_pub',
        ),
    ]
